print pwd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,23 +20,27 @@ jobs:
         uses: actions/checkout@v4
         with:
           lfs: true
+          
+      - name: echo pwd
+        run: |
+          pwd
       
       # Get build version
       - name: Check for duplicate artifact
         run: |
           cd $GITHUB_WORKSPACE
           echo -n "buildVersion=" ; grep -m 1 "bundleVersion: " ProjectSettings/ProjectSettings.asset | cut -c 18- >> $GITHUB_ENV
-
-      # Check for duplicate version
-      - name: Check artifact exists
-        uses: xSAVIKx/artifact-exists-action@v0
-        id: "artifact-exists"
-        with:
-          name: "Build-${{ env.buildVersion }}"
-      # Fail if artifact exists
-      - name: Fail if Build-${{ env.buildVersion }} already exists
-        run: exit 1
-        if: "${{ steps.check_workflow_exists.outputs.exists == 'true' }}"
+#
+#      # Check for duplicate version
+#      - name: Check artifact exists
+#        uses: xSAVIKx/artifact-exists-action@v0
+#        id: "artifact-exists"
+#        with:
+#          name: "Build-${{ env.buildVersion }}"
+#      # Fail if artifact exists
+#      - name: Fail if Build-${{ env.buildVersion }} already exists
+#        run: exit 1
+#        if: "${{ steps.check_workflow_exists.outputs.exists == 'true' }}"
         
       # Cache
 #      - uses: actions/cache@v3
