Fail workflow if build already exists

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,22 @@ jobs:
         uses: actions/checkout@v4
         with:
           lfs: true
+      
+      # Get build version
+      - name: Check for duplicate artifact
+        run: |
+          echo -n "buildVersion=" ; grep -m 1 "bundleVersion: " ProjectSettings/ProjectSettings.asset | cut -c 18- >> $GITHUB_ENV
 
+      # Check for duplicate version
+      - name: Check artifact exists
+        uses: xSAVIKx/artifact-exists-action@v0
+        id: "artifact-exists"
+        with:
+          name: "Build-${{ env.buildVersion }}"
+      # Fail if artifact exists
+      - name: Fail if Build-${{ env.buildVersion }} already exists
+        run: exit 1
+        if: "${{ steps.check_workflow_exists.outputs.exists == 'true' }}"
       # Cache
 #      - uses: actions/cache@v3
 #        with:
@@ -51,7 +66,9 @@ jobs:
           allowDirtyBuild: true
 
       # Output
-      - uses: actions/upload-artifact@v3
+      - uses: actions/upload-artifact@v4
         with:
-          name: Build
+          name: Build-${{ env.buildVersion }}
           path: build
+          compression-level: 9 # maximum compression
+          retention-days: 7 # delete after 7 days
